publishDir = "docs"
baseURL = "https://lainwireless.github.io/Pagina-Web-Hugo-2/"
languageCode = "en-us"
title = "Página Web de Iván" 
theme = "blackburn"
author = "Yoshiharu Yamashita"
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[params]
  # Shown in the home page
  subtitle = "2º ASIR"
  brand = "Blackburn"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Inicio"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Sobre mí"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 4
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  github="LainWireless"

